server:
  port: 8079

spring:
  application:
    name: gateway-ms

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        - id: productos-route
          uri: lb://PRODUCTOS-MS
          predicates:
            - Path=/api/v1/productos/**

        - id: clientes-route
          uri: lb://CLIENTES-MS
          predicates:
            - Path=/api/v1/clientes/**

        - id: empleados-route
          uri: lb://EMPLEADOS-MS
          predicates:
            - Path=/api/v1/empleados/**

        - id: sucursales-route
          uri: lb://SUCURSALES-MS
          predicates:
            - Path=/api/v1/sucursales/**

        - id: facturacion-route
          uri: lb://FACTURACION-MS
          predicates:
            - Path=/api/v1/facturacion/**

        - id: auth-route
          uri: lb://AUTH-MS
          predicates:
            - Path=/api/v1/auth/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-ms:8761/eureka
